from datetime import datetime
s = input("Informe sua data de nascimento no formato dd/mm/aa: ")
print(s)
d, m, a = s.split("/")
d= int(d)
m= int(m)
a = int(a)
print(d)
print(m)
print(a)
data= datetime(a, m, d)
print(data)